[package]
name="blog_os"
version="0.0.1"

[lib]
crate-type=["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"
spin = "0.4.6"
multiboot2 = "0.3.0"
bitflags = "1.0.3"
x86_64 = "0.1.2"
once = "0.3.3"