#[repr(C)]
struct Superblock {
    total_inodes: u32,
    total_blocks: u32,
    reserved_blocks: u32,
    unallocated_blocks: u32,
    unallocated_inodes: u32,
    block_number_containing_superblock: u32,
    log_block_size: u32,
    log_fragment_size: u32,
    blocks_in_blockgroup: u32,
    fragments_in_blockgroup: u32,
    inodes_in_blockgroup: u32,
    last_mount_time: u32,
    last_written_time: u32,
    mount_since_check: u16,
    max_mounts_since_check_allowed: u16,
    ext2_signature: u16,
    filesystem_state_code: u16,
    error_respone_code: u16,
    minor_version: u32,
    last_consistency_check_time: u32,
    forced_check_interval: u32,
    operating_system_id: u32,
    major_version: u32,
    user_id_reserved_blocks: u16,
    group_id_reserved_blocks: u16,
}
